let navigationBlock = {
  id: "granite-navigation",
  feature: "navigation",
  options: {
    type: "sidebar",
    background: "",
    background_opacity: "",
    mobile_menu: "sidebar",
    font_color: "#ffffff",
    mobile_breakpoint: "550px",
    font_size: "18px",
    topbar_padding_right: "",
    topbar_padding_left: "",
    dropdown_font_size: "12px",
    highlight: "",
    no_break_link_item: true,
    topbar_position: "right",
    topbar_over_content: false,
    topbar_font_size: "10px",
    button_style: "transparentWhite",
    cta_button_padding: "",
    single_submenu: true,
    hide_mobile_nav: false,
    header_label: "<span id='addapptation'>addapptation</span>",
    header_image: "https://addapptation.blob.core.windows.net/logo/logo.png",
    header_link: "#test",
    wrap_logo: false,
    footer: "<a href='sign-out'>Sign Out</a>",
    gradient: "",
    topbar_gradient: "",
    searching: false,
    link_label: "Sign In",
    link_url: "#",
    link_target: false,
    cta_link_left_margin: "300px",
    cta_label: "Edit",
    cta_url: "#",
    cta_target: false,
    hide_on: [],
    item_height: "65px",
    menu: false,
    use_recent_items: true,
    search_url: "search",
  },
  records: [{"label": "Home","icon": "","submenu_header": true,},],
};