let tableBlock = {
   "id": "granite-table",
   "feature": "datatable",
   "options": {
       "title": "",
       "description": "",
       "searching": false,
       "ordering": true,
       "order": [[2, "asc"],[4, "asc"],[6, "asc"]],
       "info": true,
       "dom": "lfBtip",
       "paging": true,
       "page_length": 0,
       "length_change": true,
       "scrolly": "",
       "scrollx": "100%",
       "fixedheader": false,
       "fixedcolumns": "",
       "responsive": true,
       "export_excel": false,
       "export_pdf": false,
       "export_print": false,
       "show_footer": true,
       "striped": false,
       "hover": true,
       "padded": false,
       "wrap_text": false,
       "count": true,
       "fade_table": true,
       "highlight": "#1E3D90",
     },
   "records":[

     ]
 }